name: Build and Publish NuGet Package

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    # 1. Checkout code
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Setup .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    # 3. ÂÎÑÑÒÀÍÎÂËÅÍÈÅ NuGet ïàêåòîâ (ÄÎÁÀÂËÅÍÎ)
    - name: Restore
      run: dotnet restore Kritjara.Collections.Notify.csproj

    # 4. Build project
    - name: Build
      run: dotnet build Kritjara.Collections.Notify.csproj --configuration Release --no-restore

    # 5. Create NuGet package
    - name: Pack
      run: dotnet pack Kritjara.Collections.Notify.csproj --configuration Release --no-build --output ./nupkg

    # 6. Publish to GitHub Packages
    - name: Publish to GitHub Packages
      run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_PUBLISH_TOKEN }} --source "https://nuget.pkg.github.com/Kritjara/index.json" --skip-duplicate